// <auto-generated />
namespace CarcelAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PrimeraMigracionOracle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PrimeraMigracionOracle));
        
        string IMigrationMetadata.Id
        {
            get { return "201711251523391_PrimeraMigracionOracle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
